### ISSUE TITLE
Double Contacts

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#10]
When adding some one you can get double contacts if he added you back.

![img](http://i.imgur.com/wwUhjAK.png)

How to cause it:
- Add some one to contacts (user1@diasp.net -> user2@diasp.net)
- Let same one else add you to contacts (user2@diasp.net -> user1@diasp.net)

What happens: Chaos!

It also affects when you time out from the chat:
![img](http://i.imgur.com/b2sFy5I.png)

**Comment by Flaburgan** [comment]
It doesn't seem fixed to me on the last develop code.

**Comment by Zauberstuhl** [comment]
@Flaburgan if you have multiple chat-aspects and one user is in both then you see him twice

**Comment by Flaburgan** [comment]
That's my use case. This is still a bug imo.

**Comment by Zauberstuhl** [comment]
e.g. pidgin does the same thing and it is valid in my opinion. the user is in two categories so he will be displayed in both. we could think about displaying the group name in jsxc. then it should be clear for the user.

**Comment by jhass** [comment]
I agree that the current situation is a bug. We either need to display the group name or remove the duplicates. Personally I would tend to do the later.
