### ISSUE TITLE
Chat sidebar not showing up

### ISSUE THREAD

**Issue by nicolasrpmaia** [diaspora/jsxc#101]
The pod I'm in (DiasporaBR) has recently been updated to the 0.5 version, and even though I opted to allow contacts to chat with me, the gray chat sidebar is nowhere to be found.

I am using Abrowser (Firefox derivative) on Trisquel GNU/Linux 7.0. I have tried to clear cache and cookies, have reset with addons disabled and hit hard refresh (Ctrl+F5) and no sign of it working.

Also, other users in my pod have reported being able to use the chat normally.

**Comment by jhass** [comment]
Please post the contents of your browsers error console.

**Comment by nicolasrpmaia** [comment]
Sorry, what do you mean?

**Comment by jhass** [comment]
Please access your browsers error console, clear it, reload the page and post the messages that appear.

**Comment by nicolasrpmaia** [comment]
ReferenceError: mozRTCPeerConnection is not defined

Possibly because I disabled WebRTC?

**Comment by jhass** [comment]
Sounds like it.

**Comment by nicolasrpmaia** [comment]
For reference, that was the issue. Enabling WebRTC again made it work.
