### ISSUE TITLE
Same username shows up twice in the chat after refreshing the page

### ISSUE THREAD

**Issue by theworldbright** [diaspora/jsxc#104]
Branch: Latest develop

Steps to reproduce:

1. Enable a two way subscription with any user on the chat
2. Open up the chat
3. Refresh the page

![screen shot 2015-06-30 at 4 48 26 pm](https://cloud.githubusercontent.com/assets/6329898/8426146/294f6b0a-1f48-11e5-8c6e-d2110b210135.png)

**Comment by theworldbright** [comment]
Oh I just noticed #89.

**Comment by Zauberstuhl** [comment]
duplicate. closing it
