### ISSUE TITLE
JSXC diaspora alpha channel

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/jsxc#120]
Fla you ask whether we can create a alpha (old stable) channel for jsxc.
Right now, there would be some conflicts related to bootstrap3 (different heights/widths)

The port is not complicated but I would wait till we have bootstrap3 in the alpha branch
then we shouldn't be afraid of nasty merge conflicts.

Objections?

@Flaburgan @AugierLe42e @svbergerem

**Comment by AugierLe42e** [comment]
I'd wait too. I'd like to have a debug period to tests this on multiple pods. We are going to enable on diaspote soon.

**Comment by Flaburgan** [comment]
Well the stable (== minor) branch is not going to have the bootstrap port until we release a new major version (develop branch), which will already include the fixes.

**Comment by Zauberstuhl** [comment]
so you favour the alpha branch now. when is the next major?

**Comment by AugierLe42e** [comment]
> so you favour the alpha branch now. when is the next major?

No date if I'm correct. But nothing urges. 0.6 might the most important community release diaspora have had.
