### ISSUE TITLE
Contacts list in fixed position?

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#123]
I find a bit weird that opening the contacts list move all the page to the left. Is it a design choice not to place it in a fixed position?

**Comment by Zauberstuhl** [comment]
from my perspective; yes it is.

we could talk about letting the user decide.
jsxc has a option for this: `jsxc.options.displayRosterMinimized`

but the user should be able to hide the chat!

**Comment by AugierLe42e** [comment]
Nope, that was not my question. From my point of view, opening the chat should be done *over* the stream and not push it to the left.

**Comment by Zauberstuhl** [comment]
on smaller screens you wouldn't be able to read the stream while the contact list is visible.

**Comment by AugierLe42e** [comment]
Well the right bar is large enough, don't you think?

**Comment by Zauberstuhl** [comment]
not on my netbook, no

**Comment by AugierLe42e** [comment]
Alright. Closing this, then.
