### ISSUE TITLE
Roster not sticked to header with custom height

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#128]
Since you manually set the top position of the roster [here](https://github.com/diaspora/jsxc/blob/develop/build/css/jsxc.css#L2864), it creates problems with custom header like e.g on diaspote where header is 46px. I don't know if you can access to [the variable](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/bootstrap-variables.scss#L361) from the gem. I'd say not so probably it's better to define this rule [here](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/chat.scss).

**Comment by Zauberstuhl** [comment]
could you implement this? I had my problems with it. I am not sure if this even works across packages.
Maybe someone with more assets knowledge can help :)

**Comment by AugierLe42e** [comment]
Yep, this has to be set in [this file](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/chat.scss) I open a PR tonight.

**Comment by Zauberstuhl** [comment]
<3 danke

**Comment by AugierLe42e** [comment]
Bitte.

**Comment by Zauberstuhl** [comment]
closing in respect of https://github.com/diaspora/diaspora/pull/6567
thanks
