### ISSUE TITLE
request to update jquery to 1.11.3

### ISSUE THREAD

**Issue by pravi** [diaspora/jsxc#134]
debian already has 1.11.3 and this will help in keeping debian package in sync with upstream dependency chain.

**Comment by Zauberstuhl** [comment]
@pravi what about jquery 2? should we use it instead of 1.11.3? (see the related diaspora ID)

**Comment by Zauberstuhl** [comment]
just had a little research on my own seams like there is only 1.11.3 for debian right?
I will switch to 1.11.3 and mention this in the diaspora id.

**Comment by pravi** [comment]
@Zauberstuhl yes, currently we have 1.11.3 and 3.0.0 alpha1 but we can't use it yet. Also please make it ~> 1.11.3

Let me check with my team if we can move to jquery 2 in debian.

**Comment by terceiro** [comment]
please just use `>= 1.11` since jquery is backwards compatible except for browser support ...
