### ISSUE TITLE
XMPP chat web interface isn't working

### ISSUE THREAD

**Issue by hfroese** [diaspora/jsxc#146]
Hi guys,
external clients like Pidgin can login / connect to my diaspora server but the web interface isn't working.
![bildschirmfoto vom 2016-01-14 18 01 36](https://cloud.githubusercontent.com/assets/1968490/12331204/e330d478-bae8-11e5-84c2-ac65ddcafb26.png)
[vines.log.txt](https://github.com/diaspora/jsxc/files/90710/vines.log.txt)

**Comment by Flaburgan** [comment]
Same problem for me on diaspora-fr.org, maybe since the upgrade to 1.4. @augierLe42 @SansPseudoFix is the chat working for you on d-fr? @asterismo also has similar problem on his pod.

**Comment by SansPseudoFix** [comment]
Well, it seems to work now.

**Comment by Flaburgan** [comment]
Wow, I get it! It's because we are offline by default, and when offline the roster isn't populated...

**Comment by asterismo** [comment]
i'll upgrade to 0.5.6 now and will report back

**Comment by asterismo** [comment]
i'm using prosody 0.10 and @jhass told me he did not tried the diaspora modules with that prosody version. I'm trying to upgrade diaspora to 0.5.6.0 now, but i'm having some problems. In the mean time, i wanted to comment that i can use the chat, but it seems that diaspora contacts are not loaded. As you see in the screenshot, i have many contacts, but they were added using Jitsi and they are not diaspora contacts nor have diaspora accounts whatsoever. The chat runs fine but it has a small bug which is when someone adds you as a contact and then gets disconnected, the notification dialog stays up after pressing add/allow on the user.
![diaspora_chat](https://cloud.githubusercontent.com/assets/5679035/12333432/ef12a714-bad2-11e5-865e-996a4252e837.jpeg)

**Comment by hfroese** [comment]
My chat never worked with the web client but pidgin. Even not on 5.5.0

**Comment by asterismo** [comment]
I talked to the prosody guys at their chatroom and they helped me a lot on getting a clean prosody conf file, are you using vines @hfroese?

**Comment by hfroese** [comment]
Jipp - just vines - no external server

**Comment by hfroese** [comment]
I don't know if its relevant but in vines.log there is an error:
  <stream:error>
    <unsupported-version xmlns="urn:ietf:params:xml:ns:xmpp-streams"/>
  </stream:error>

**Comment by hfroese** [comment]
I don't know if its relevant but in vines.log there is an error:
  stream:error
    unsupported-version xmlns="urn:ietf:params:xml:ns:xmpp-streams"/
  /stream:error

**Comment by Zauberstuhl** [comment]
yes it is probably vines related I like check it out asap

**Comment by Zauberstuhl** [comment]
Closing since we moved officially to prosody
