### ISSUE TITLE
JSXC using non-SSL connection

### ISSUE THREAD

**Issue by TwizzyDizzy** [diaspora/jsxc#157]
Hi folks,

I'm not quite sure whether this is an issue of JSXC itself or the implementation from diaspora's side. Still, I think this is the right place evaluate how to move on from here.

I have a diaspora instance that has just been upgraded to 0.6. After that I tried enabling the XMPP chat feature.

Prerequsites:

* pod is reachable via https://pod.thomasdalichow.de
* Prosody 0.10-nightly (connection via XMPP using the diaspora auth has successfully been tested)
 * XMPP Server is reachable via pod.thomasdalichow.de:5281
* No unencrypted connections possible (port 5280 is not listening!)
* running the following configuration in XMPP settings in diaspora.yml:

>   chat:
>     enabled: true
>     server:
>       enabled: false

* BOSH is enabled and working on port 5281 (encrypted)

When the JSXC webcient tries to connect, the browser is throwing the following error on the console:
> Mixed Content: The page at 'https://pod.thomasdalichow.de/stream' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pod.thomasdalichow.de:5280/http-bind'. This request has been blocked; the content must be served over HTTPS

As we can see, the JSXC webclient tries to connect

* via http (http://pod.thomas....)
* on the wrong port ( [...]dalichow.de:5280/http-bind)

Is there any misconfiguration on my pod or is this an JSXC issue? Please do not hesitate to ask further questions, I'll reply shortly.

Cheers
Thomas

**Comment by Zauberstuhl** [comment]
Hi, set `proxy` to true and configure your web server according to the integration wiki -> https://wiki.diasporafoundation.org/Integration/Chat#Browser_blocks_mixed-content

**Comment by TwizzyDizzy** [comment]
Hi Zauberstuhl,

Indeed, I haven't had set the proxy setting, with it enabled it now works as expected!

The yaml format is somewhat misleading in that respect since I thought that "proxy" doesn't take effect if "server:enabled" is "false".

Anyway, thanks for having a look, your help is appreciated :)

Cheers
Thomas
