### ISSUE TITLE
Logout process

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/jsxc#22]
Currently I registered the event on our Diaspora logout button, see https://github.com/diaspora/jsxc/blob/develop/jsxc.lib.js#L294 and https://github.com/Zauberstuhl/diaspora/blob/xmpp_chat_feature/app/assets/javascripts/jsxc.js#L10

That has the effect that you have to click two times on the button.

**Comment by AugierLe42e** [comment]
@Zauberstuhl : #7 solved this problem, right ?

**Comment by Zauberstuhl** [comment]
Nope this is still a problem. #7 was something different (misleading title).
