### ISSUE TITLE
Require to reconnect?

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#38]
Hello there,

You are required to reconnect after browsing to a different pages is this intended?

//Edit:

It happens not all the time, usually it is random.

![img](http://i.imgur.com/a3FhJDT.png)

**Comment by AugierLe42e** [comment]
@Anime-Machina : Do you still have this bug ? It seems to be fixed on d-fr.

**Comment by Anime-Machina** [comment]
It got confirmed earlyer, it was fixed thanks to a NGINX Config edit ^^
