### ISSUE TITLE
Chat entirely disapeares

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#39]
I reported this a wile ago apparently it is still not fixed:

Wile browsing Diaspora you end up in losing the chat panel (Right Sidebar) including all windows during browsing. The only way to fix this (temporarly) is clearing all cookies and application data.

Browser: Google Chrome, Iceweasel, FireFox
Remake the bug: Browse Diaspora* and use the middle mouse button, load a different page and voila!

**Comment by AugierLe42e** [comment]
@Anime-Machina : fixed too, isn't it ?

**Comment by Anime-Machina** [comment]
It got fixed, just verified although I should have confirmed it a wile ago. My bad :)
