### ISSUE TITLE
Terminology: jsxc by talks about buddies

### ISSUE THREAD

**Issue by jhass** [diaspora/jsxc#40]
At diaspora we take to care to use the term contact. Not all your social contacts are your friends or your buddies.

Should we try to convince upstream to change that? Or should we maintain our own localization?

**Comment by jhass** [comment]
https://github.com/diaspora/jsxc/blob/develop/locales/en.json#L6

This is still not fixed. Now that our translations are upstream, how will we handle this?

**Comment by Zauberstuhl** [comment]
well, we should request that change in jsxc webtransletit or use our own locales?

**Comment by jhass** [comment]
Great, you understood my question. If I knew I wouldn't have started this issue with exactly this question!

**Comment by Zauberstuhl** [comment]
https://webtranslateit.com/en/projects/10365-JSXC/discussions/43216

**Comment by sualko** [comment]
Is someone working on this, or can I start changing the english translation?

**Comment by jhass** [comment]
I don't think anybody is.

**Comment by sualko** [comment]
Ok, then I start.

**Comment by sualko** [comment]
Should be done.

https://webtranslateit.com/en/projects/10365-JSXC/activities/641778

**Comment by jhass** [comment]
Alright, looks good.

I proofread them, while doing so I replaced "he or she" with the gender neutral singular "they" and left those unproofread for somebody to verify.

I also noticed a few strings that are apparently concatenated to other translations or strings. I flagged them as to verify since concatenation assumes a certain grammar, that works for many eastern language in a similar manner, but in some case those get impossible to translate, especially if go into the asian languages, since the grammar is very different. You should eventually try to use interpolation everywhere.
