### ISSUE TITLE
When clicking 'Relogin' your page refreshes and nothing happens.

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#49]
Hello there again,

Updated diaspora* this morning to the latest commit, there is a bug when clicking the 're login' button. It minimizes the chat window to the right side and refreshes the page but it does not log you in. Although I am also connected trough bitlbee if that makes a difference.

Just to make things clear the button teases me allot :[

![IMG](http://i.imgur.com/A48NpLK.png "Teasing Link")

**Comment by AugierLe42e** [comment]
This has been solved, isn't it ?

**Comment by Anime-Machina** [comment]
I beleave it got fixed at JSXC 9.2, but it still bugs out some times
(rarely)

**Comment by Anime-Machina** [comment]
Yes it got fixed, close it!
