### ISSUE TITLE
Chat window times out too shortly

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#60]
I noticed the chat times out in about 2 minutes and personally I think it could be extended to atleast 30 minutes?

//rethought:
Personally I think there is a bit of a personal flavor to this so could it be added to the config?

**Comment by Flaburgan** [comment]
@Zauberstuhl I confirm this is an annoying issue. I just activated the chat on diaspora-fr.org, please ping me on IRC and I'll give you an invite to test the chat on my pod ;)

**Comment by Zauberstuhl** [comment]
@Flaburgan I already have a test account sechat@diaspora-fr.org. I will look into that asap

**Comment by Zauberstuhl** [comment]
This is probably not related to jsxc. It seams it is a problem with nginx (sechat.org uses apache).

@Flaburgan could you change your ngninx config to something like that:

```
upstream chat_cluster {
  server localhost:5280;
}
 
location /http-bind {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-Proto https;
 
  proxy_redirect off;
  proxy_connect_timeout 5;
  proxy_buffering       off;
 
  proxy_read_timeout    70;
  keepalive_timeout     70;
  send_timeout          70;
 
  client_max_body_size 4M;
  client_body_buffer_size 128K;
 
  proxy_pass http://chat_cluster;
}
```

diaspora-fr runs into multiple 504 errors so adjusting nginx-timeouts according to http://www.getvines.org/server/cluster/ should fix your problem (I updated the wiki).

**Comment by Flaburgan** [comment]
@Zauberstuhl conf updated. Let's make a test.

**Comment by Anime-Machina** [comment]
\o/ updates!

**Comment by Flaburgan** [comment]
Looks like it doesn't timeout anymore.

**Comment by Zauberstuhl** [comment]
@Anime-Machina can you confirm that? you have also a nginx setup.

**Comment by Anime-Machina** [comment]
I will once I get home, currently at my bank /o\

**Comment by Anime-Machina** [comment]
I tested it for a couple of days by signing in (still using bitlbee), longest test is about 30 minutes. It did not timed out so far. Good job @Zauberstuhl
