### ISSUE TITLE
Can't add buddy

### ISSUE THREAD

**Issue by wiltur** [diaspora/jsxc#64]
Hi, 
I can active chat, login, but it's not possible to add a buddy to the chat, nothing appened when clicking on Add_buddy .

I'm on diaspora-fr.org using firefox 34.

**Comment by Flaburgan** [comment]
@wiltur you have to go to your contact page and activate the chat for the aspects you want.

**Comment by wiltur** [comment]
ho, ok, sorry, i get it now :)

**Comment by Zauberstuhl** [comment]
we should definitely create a help page in diaspora for that (https://wiki.diasporafoundation.org/Vines#I_have_no_contacts_in_my_roster).
