### ISSUE TITLE
Working+Optimized NGINX configuration

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/jsxc#8]
I am the podmin of Diasp.net and running this version of Diaspora* for helping the development and high demand for it. Although it is very buggy but here I would like to share my nginx config with optimized SSL security.

[NGINX Working+Optimized Config](https://gist.github.com/Anime-Machina/dd610a887b1d9c8994cb)

Although knowing which version to run from this repo would be useful ;)

**Comment by Zauberstuhl** [comment]
this belongs to the wiki see https://wiki.diasporafoundation.org/Vines

following the official diaspora update guide will install the latest version of jsxc!
