### ISSUE TITLE
Always display the chat

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/jsxc#83]
I looked at this, looks like there are some simple changes to do on the CSS. I'm going to create a pull request before the end of the week. Sorry I'm quite busy currently hosting @marienfressinaud at home ;)
##

**Comment by Flaburgan** [comment]
We have to deal with the back-to-top button though, it is actually hidden behind the chat. I'd like to check how https://github.com/diaspora/diaspora/pull/5247 is dealing with this button.

**Comment by svbergerem** [comment]
@Flaburgan That is no big deal. I already implemented it but it broke in #63. We just need to add the class `chat-roster-shown` to `body > .container` like I did in #42 and everything should be fine.

**Comment by AugierLe42e** [comment]
@Flaburgan : be sure to not make duplicate work with #82  ;)

**Comment by Zauberstuhl** [comment]
can we close this one?

**Comment by Flaburgan** [comment]
The chat is not displayed on every pages actually, what have changed which can close this?

**Comment by Zauberstuhl** [comment]
Its not an jsxc issue and its tracked via https://github.com/diaspora/diaspora/issues/6143

**Comment by Flaburgan** [comment]
Forgot about this comment sorry, sure we can close it here.
