### ISSUE TITLE
Display pseudonym instead of handle

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#85]
All is in the title. I don't think this information already exists in the JSXC data structure, right ?

**Comment by Zauberstuhl** [comment]
with the newest dev version we display first plus last name instead of handle.

**Comment by AugierLe42e** [comment]
Dev version of Vines ?

**Comment by Zauberstuhl** [comment]
yes wasn't released yet

**Comment by AugierLe42e** [comment]
Ok, closing it, so.
