### ISSUE TITLE
Diaspora customization got lost

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/jsxc#86]
Since upstream ported all css to scss our diaspora customization got lost.

https://gist.github.com/f853d5e84df5adb60596

**Comment by AugierLe42e** [comment]
Hmm... There's more than this missing. The changes instroduced in #82 .

**Comment by Zauberstuhl** [comment]
yes everything related to css. @AugierLe42e btw should we get rid of #11 in respect of #83?

**Comment by AugierLe42e** [comment]
I think chat window should be hidable. It is not anymore on FB and I found this pretty annoying. But, of course, it should be displayed byt default on connection.

**Comment by Zauberstuhl** [comment]
of course it should be hide-able. I am talking about the big gray click thing. Currently it is back to original `width:14px` you adjusted it to `width:34px`.

My opinion is that we should leave the 14 px cause the user will be aware of the chat anyway :)

**Comment by AugierLe42e** [comment]
Initial problem was `14px` was not easy to click on.
Question is : do we want to customize the chat as least as possible ? If no, I can work on another way to display the chat. With may the hiding bar at the top instead on the left.

**Comment by AugierLe42e** [comment]
Oh, shit @Zauberstuhl , we need to fix this quick. I hadn't seen yet what it looked like but this is... AAAARRG

**Comment by Zauberstuhl** [comment]
what do you mean with disconnect?

**Comment by AugierLe42e** [comment]
I need sometimes 2 times click on disconnect to really disconnect.

**Comment by Zauberstuhl** [comment]
you are talking about the logout button on the nav-bar. That is right. That sucks ;)
But that is a old problem check #22

**Comment by AugierLe42e** [comment]
I though it was solved ?
