### ISSUE TITLE
Daltonian mode ?

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#93]
This has been requested by friend of mine. JSXC uses blue, grey, yellow and red colors which are not easy to distinguish colors for daltonian. A simple CSS override could do the trick.

It would be an opt-in mode, obviously.

**Comment by Flaburgan** [comment]
Maybe we can report that upstream?

**Comment by AugierLe42e** [comment]
I think it may be nice.

**Comment by AugierLe42e** [comment]
Closing it as [proposed to upstream](https://github.com/jsxc/jsxc/issues/137).
