### ISSUE TITLE
Messages for offline contacts end up in message box ?

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#97]
Hey, this is an idea I'va had this morning. What if the messages for offline contacts ended up in message box ?
About the implementation, I thought about the possibility to specify a callback in JSXC lib that can be filled on initialisation ?
@Zauberstuhl : What do you think about the idea ?

**Comment by Zauberstuhl** [comment]
honestly I don't like it in respect of spamming. If you receive 10 offline messages you get 10 email notifications. also such functionality is better handled in the back-end.

**Comment by AugierLe42e** [comment]
>  If you receive 10 offline messages you get 10 email notifications. 

Well I though all the message could be sent under the same object, e.g "Offline chat", what do you think ?

**Comment by Zauberstuhl** [comment]
that wouldn't change the result. If you want to implement it feel free and make a proposal

**Comment by AugierLe42e** [comment]
Ok, I trust you.

**Comment by Zauberstuhl** [comment]
@AugierLe42e if you want to implement it Vines and Diaspora have to talk to each other.
